### ISSUE TITLE
Build project have error:

### ISSUE THREAD

**Issue by molyswu** [Qualeams/Android-Face-Recognition-with-Deep-Learning-Test-Framework#1]
Hi, 
Error:(27, 0) Project with path ':facerecognitionlibrary/' could not be found in project ':app'.

?
Thank you!
Molys wu

**Comment by sladomic** [comment]
Hello, did you clone the repo with the "--recursive" flag?

If not you can still try "git submodule init" and then "git submodule update".

Regards,
Michael
