### ISSUE TITLE
cpu run slowly

### ISSUE THREAD

**Issue by molyswu** [Qualeams/Android-Face-Recognition-with-Deep-Learning-Test-Framework#10]
When  I open the camera, Android to run slowly, I think you do not have to deal with OpenGL frame。

Thanks you for your help!

**Comment by sladomic** [comment]
Hi,

What is exactly the question? With which settings are you running the app?

The frame rate is bad, because of the heavy processing in each frame. You could try to run the processing in a background thread and/or to use the NativeCameraView of OpenCV instead of the JavaCameraView.

Regards,
Michael

**Comment by molyswu** [comment]
Hi ,sladomic .
1.How to deal with background threads or to use the NativeCameraView of OpenCV instead of the JavaCameraView？Could you please help me to explain how to change the code。
2.I have put vgg_face.pb, vgg_face_caffe, tensorflow_inception_graph.pb on SD card, and then add person, Recognition Training, Recognition Test, Recognition View, but can not identify.


Thank you for your help!

molysWu

**Comment by sladomic** [comment]
Hi,

1. You can try to do it like here https://github.com/sladomic/literacyapp-android/blob/master/app/src/main/java/org/literacyapp/authentication/AuthenticationActivity.java and here https://github.com/sladomic/literacyapp-android/tree/master/app/src/main/java/org/literacyapp/authentication/thread
2. Did you adjust the settings?

- Preprocessing Recognition: Only "Crop" and "Resize" and N = 224
- Recognition Algorithms General: Feature extraction and classification method "TensorFlow with SVM or KNN"
- TensorFlow: Input Size = 224, Output size = 4096, Input layer = Placeholder, Output layer = fc7/fc7, Model file = vgg_faces.pb

**Comment by molyswu** [comment]
Hi,
Did android reboots sometimes when opens the Recognition Training or Recognition Test?

Thank you very much!

molysWu

**Comment by sladomic** [comment]
If that happens, your device might be too less powerful for the vgg_faces network, which requires a lot of RAM. I'm currently working on shrinking this network. Best would be if you wait a few days, until I can upload a smaller version.

**Comment by sladomic** [comment]
@molyswu I added a new function setMaxFrameSize. You can set the max width and max height in the settings. You get a better performance now if you use a smaller frame size (e.g. 640 x 480 or 320 x 240 instead of 1920 x 1080).

**Comment by molyswu** [comment]
Hi,
You  solve the problem of slow running open camera Android, Recognition View no prompt word？
 Recognition Training and Recognition Test successful。

Thank you very much!

molysWu
