### ISSUE TITLE
JNI functions not detected using latest gradle version

### ISSUE THREAD

**Issue by ashokbugude** [Qualeams/Android-Face-Recognition-with-Deep-Learning-Test-Framework#15]
I have setup 'Android-Face-Recognition-with-Deep-Learning-Test-Framework' in Android Studio (latest version) with latest gradle version

The project builds fine. 
But when I open files under 'Recognition' folder under 'facerecognitionlibrary',for eg TensorFlow.java,

native functions like 
 initializeTensorflow, classifyImageBmp, classifyImageRgb are not resolved and appear red as shown in attached pic.

<img width="938" alt="jnifunctionserror" src="https://cloud.githubusercontent.com/assets/10016848/26317891/b7877560-3f36-11e7-9b41-7ecbe3fa1b21.PNG">

With error message like **'Cannot resolve corresponding JNI function Java_ch_zhaw_facerecognitionlibrary_Recognition_TensorFlow_initializeTensorflow'** for initializeTensorflow method 

I think the latest gradle versions make use of cmakelists.txt , instead of android.mk or applications.mk
Could I please know the contents of cmakelists.txt according to latest version of gradle

**Comment by sladomic** [comment]
@ashokbugude even though the jni functions are red, it should still work. However TensorFlow has released so many updates lately, that I will replace this implementation with the Jcenter library of TF (they just showcased it at Google I/O).

**Comment by ashokbugude** [comment]
@sladomic Thanks, I am still wondering how the linker issue is resolved internally.

**Comment by ashokbugude** [comment]
Please update us once updated version of TensorFlow is integrated
Thanks
