### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by ashokbugude** [Qualeams/Android-Face-Recognition-with-Deep-Learning-Test-Framework#16]
Hi , I have setup the project in Android Studio, but when I build it , I get below errors

**Error:error:** '-Wno-error=unused-function': No such file or directory
**Error:error:** '-std=c++11': No such file or directory
**Error:error:** '-std=c++11': No such file or directory
**Error:error:** '-DMIN_LOG_LEVEL=0': No such file or directory
Information:BUILD FAILED

Please help in resolving it

**Comment by sladomic** [comment]
Hi @ashokbugude 

What are you trying to do exactly? The native libs are build separately (not included in Grafle and Android Studio). But you don't need to build the native libs, because they are already included under https://github.com/Qualeams/Android-Face-Recognition-with-Deep-Learning-Library/tree/49125122ca1db5720b8be2d8cefbafdbc3ec4010/src/main/jniLibs

**Comment by ashokbugude** [comment]
Hi @sladomic , I am trying to do research on 'parallel programming' for the Tensor Flow code through ndk and opencl by modifying the source code in tensorflow_jni.cc and its related code and then rebuild the library and use it. Please help me in rebuilding the library, will refer to your comment in https://github.com/Qualeams/Android-Face-Recognition-with-Deep-Learning-Test-Framework/issues/17 
Thanks

**Comment by sladomic** [comment]
Ok, please try that approach first and return if you're not successful. Good luck :)

Another approach would be to use the Bazel build system which is used by TensorFlow usually. Should be easier once you have setup the whole environment. https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/README.md

Although for me honestly both processes are not straightforward at the moment..

**Comment by ashokbugude** [comment]
@sladomic , I shall look into it and try. Closing the issue, Please update me in case you are able to implement it
Thanks

**Comment by ashokbugude** [comment]
Able to build by following the steps in Qualeams/Android-Face-Recognition-with-Deep-Learning-Library#1. Thanks for your help
