### ISSUE TITLE
Unable to debug ndk code using breakpoints in Android Studio

### ISSUE THREAD

**Issue by ashokbugude** [Qualeams/Android-Face-Recognition-with-Deep-Learning-Test-Framework#22]
Hi
I tried all possible ways to try debugging ndk code using Breakpoints, but coudn't acheive it.
Could I please know if you were able to hit breakpoints in ndk code, if so please tell any additional settings you have made

Thanks

**Comment by sladomic** [comment]
With this current setup I wasn't able, no. But Google only included this a few months back I think. You would need to watch some of the latest tutorial videos for NDK debugging in Android Studio because I think they changed a lot.

**Comment by ashokbugude** [comment]
Thanks, I was able to debug when I use 'Cmakelists.txt' instead of 'Android.mk'
Incase you were able to debug using 'Android.mk', please let me know

**Comment by venkateshpappu** [comment]
Hello ashok, how can i hit the breakpoints using ndk/cmake, can you please tell me

**Comment by ashokbugude** [comment]
Hi Sorry, I haven't been able to hit breakpoints

**Comment by venkateshpappu** [comment]
Thanks for the reply, which version of android studio you are using

**Comment by ashokbugude** [comment]
I am using 2.3.3 version
