### ISSUE TITLE
Printing TensorFlow Library Logs in Android Studio

### ISSUE THREAD

**Issue by ashokbugude** [Qualeams/Android-Face-Recognition-with-Deep-Learning-Test-Framework#23]
I have built Tensor Flow using Bazel and am using the generated TensorFlow Libraries in Android Studio
for ndk.

But I do not find the logs of Tensor Flow being printed in Android Studio.
Can I know how do I acheive this .

I have tried using Android/log.h in TensorFlow code but of no use

**Comment by sladomic** [comment]
This is the way it is done in tensorflow_jni.cc
LOG(INFO) << "Loading Tensorflow.";

**Comment by ashokbugude** [comment]
Hi I wanted the logs from TensorFlow code
For Eg : Session -> Run (parameters) in tensorflow_jni.cc executes Direct_seesion.cc from Tensor Flow.
I wanted to print log Statements in Direct_session.cc in TensorFlow and build the library and use the library in Android and view the logs printed in Direct_session.cc ( from the library)

OR

Is there any other way to debug the code executed from the libtensorflow.so file ?
