### ISSUE TITLE
Any demonstration videos for the app?

### ISSUE THREAD

**Issue by shivakrishna9** [Qualeams/Android-Face-Recognition-with-Deep-Learning-Test-Framework#24]

**Comment by sladomic** [comment]
Hi @shivakrishna9 not really, but here's a user manual for the first version we had:
https://github.com/Qualeams/Android-Face-Recognition-with-Deep-Learning-Test-Framework/blob/master/USER%20MANUAL.md
we didn't have time to update this manual with the updates we made, but the basics should still be valid
