### ISSUE TITLE
Getting compile time error.

### ISSUE THREAD

**Issue by arnab-kundu** [Qualeams/Android-Face-Recognition-with-Deep-Learning-Test-Framework#31]
Error:com.android.builder.internal.aapt.AaptException: Failed to crunch file C:\Users\akundu\AndroidStudioProjects\Android-Face-Recognition-with-Deep-Learning-Test-Framework-master\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.3.0\res\drawable-ldrtl-hdpi-v17\abc_ic_ab_back_mtrl_am_alpha.png into C:\Users\akundu\AndroidStudioProjects\Android-Face-Recognition-with-Deep-Learning-Test-Framework-master\app\build\intermediates\res\merged\debug\drawable-ldrtl-hdpi-v17\abc_ic_ab_back_mtrl_am_alpha.png

**Comment by sladomic** [comment]
seems to be a file path problem in Windows https://stackoverflow.com/a/39621978
