### ISSUE TITLE
Error:Failed to resolve: org.tensorflow:tensorflow-android:1.2.0-rc0

### ISSUE THREAD

**Issue by devillee** [Qualeams/Android-Face-Recognition-with-Deep-Learning-Test-Framework#32]
Error:Failed to resolve: org.tensorflow:tensorflow-android:1.2.0-rc0
<a href="openFile:D:/Develope/ASWork/Android-Face-Recognition-with-Deep-Learning-Test-Framework-master/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by sladomic** [comment]
Seems like tensorflow has moved their packages from tensorflow-android to tensorflow on Jcenter

https://bintray.com/bintray/jcenter/org.tensorflow%3Atensorflow

So you need to replace tensorflow-android with tensorflow in the gradle file

**Comment by devillee** [comment]
thanks
