### ISSUE TITLE
Desktop Verison

### ISSUE THREAD

**Issue by Subh1m** [Qualeams/Android-Face-Recognition-with-Deep-Learning-Test-Framework#34]
Hi,

Loved your project and would like to use it for another. Do you have a desktop version or something that can be run on a server for scalability? Preferably python, if not a problem. Would really appreciate it.

**Comment by sladomic** [comment]
We don't have the code on other platforms than Android. I would probably try this https://github.com/davidsandberg/facenet

**Comment by Subh1m** [comment]
Thanks for the suggestion, would it be fine if you could send me an email : biswas.subham1@gmail.com

Will be of great help if I have any queries or discussion.
