### ISSUE TITLE
I thinks it not correct.

### ISSUE THREAD

**Issue by hnptvtoan** [Qualeams/Android-Face-Recognition-with-Deep-Learning-Test-Framework#36]
![photo6168086526622279684](https://user-images.githubusercontent.com/23209132/37747320-3869bb0c-2db1-11e8-8f08-9bc9d122481a.jpg)

**Comment by sladomic** [comment]
@hnptvtoan Have you trained both persons or only St 7? Please note, that the face recognition will classify a new face with the most similar trained one.

Also which settings/algorithms did you use?

**Comment by hnptvtoan** [comment]
@sladomic  i trained only St 7 = right image.

**Comment by sladomic** [comment]
Please check https://github.com/Qualeams/Android-Face-Recognition-with-Deep-Learning-Library/issues/13 for more information

**Comment by chithrabaskar** [comment]
is there any way to detect new face????
