### ISSUE TITLE
Out of Memery Error when using a trained tensorflow model to android platform

### ISSUE THREAD

**Issue by TBJ1027** [Qualeams/Android-Face-Recognition-with-Deep-Learning-Test-Framework#38]
Hi, Im a senior student in China, and im trying to use a face-recognition model i've trained with tensorflow framework in android platform. But there is a problem when importing the model as shown below.
04-30 03:55:34.143 1766-1766/? E/art: Throwing OutOfMemoryError "Failed to allocate a 111118082 byte allocation with 1048576 free bytes and 94MB until OOM"
It reminds me my model is too large to import(my model's size is 108514KB which is similar to ur tensorflow model). So im eager to know how do u solve the problem. Thank u so much!

**Comment by sladomic** [comment]
Have you tried another device or to reboot? Probably the memory is still allocated from another process.

**Comment by TBJ1027** [comment]
thx for such a quick response, i havent try on another device, but i have tried to reboot my phone, Do u mean it is my phone's problems?

**Comment by TBJ1027** [comment]
I solve the problem of mine! I try another device and add a line of code "android:largeHeap="true"" in the AndroidManfest.xml. Thank u for helping me!
