### ISSUE TITLE
Face liveness detection

### ISSUE THREAD

**Issue by Prasad2018** [Qualeams/Android-Face-Recognition-with-Deep-Learning-Test-Framework#42]
While Trying to access with mobile photos , App recognition was granted. How do i make changes to not allow the mobile photos for accessing the application.

**Comment by NabanilC** [comment]
> While Trying to access with mobile photos , App recognition was granted. How do i make changes to not allow the mobile photos for accessing the application.

Any update on this?

**Comment by sladomic** [comment]
Duplicate of https://github.com/Qualeams/Android-Face-Recognition-with-Deep-Learning-Test-Framework/issues/45
