### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by Sparker0i** [Qualeams/Android-Face-Recognition-with-Deep-Learning-Test-Framework#49]
Hi, is there any method through which we can bring in a pre-trained model from our PCs? If yes, then what models will the app support?

**Comment by sladomic** [comment]
Hi, you have to export the graph as a pb and freeze the variables (freeze graph script) and you can remove unused operations for inference (strip unused nodes script). You can use any model as long as the operations are supported on mobile. I would recommend to use mobile first models like MobileNet / NasNet-Mobile though, if you have free hand to decide, for better speed.

Also you could switch from the tensorflow-android library, which is outdated to the tensorflow lite library or use Firebase ML-Kit and with both of them you could follow the more up to date guides for converting a graph to TF lite format.

**Comment by Sparker0i** [comment]
Hi, Thanks for the reply. I have followed one of the [tutorials](https://krasserm.github.io/2018/02/07/deep-face-recognition/). It uses keras, but I was able to convert it to a frozen .pb graph, thereafter also to a .tflite format. Now how do I use that file in the application?

**Comment by sladomic** [comment]
The frozen graph should work after removing unused operations: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/graph_transforms#optimizing-for-deployment

**Comment by Sparker0i** [comment]
> The frozen graph should work after removing unused operations: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/graph_transforms#optimizing-for-deployment

I get that. I don't understand how will I use my frozen graph inside this application.

**Comment by sladomic** [comment]
You have 2 options:
1. place the model in the directoy **/sdcard/Pictures/facerecognition/data/TensorFlow/**
2. place the model in the [assets folder](https://github.com/Qualeams/Android-Face-Recognition-with-Deep-Learning-Library/tree/master/facerecognitionlibrary/src/main/assets) of the app

and change the settings accordingly:
![Screenshot_20190316_145707](https://user-images.githubusercontent.com/556222/54476295-e3757580-47fb-11e9-92f4-25a7df4f29b3.jpg)

**Comment by Sparker0i** [comment]
Thanks. This is what I wanted to know

**Comment by Sparker0i** [comment]
I had another doubt. After placing the .pb in assets folder, will it be automatically recognized by the app, or do we have to make some changes to the code as well?

**Comment by sladomic** [comment]
It should work right away, if you provide the correct name in the settings (and other parameters such as input layer or input size). This is the code, which loads the model: https://github.com/Qualeams/Android-Face-Recognition-with-Deep-Learning-Library/blob/master/facerecognitionlibrary/src/main/java/ch/zhaw/facerecognitionlibrary/Recognition/TensorFlow.java#L74
