### ISSUE TITLE
Is there some way to print the name of the person detected on screen?

### ISSUE THREAD

**Issue by Aman2612** [Qualeams/Android-Face-Recognition-with-Deep-Learning-Test-Framework#57]

**Comment by sladomic** [comment]
The name is already printed on the output video. Or what do you mean instead?

**Comment by Aman2612** [comment]
I'm not sure why it isn't getting printed on my screen. How can i proceed with this?

The rectangle is drawn perfectly but the name isn't printed.

**Comment by sladomic** [comment]
Have you followed these steps? https://github.com/Qualeams/Android-Face-Recognition-with-Deep-Learning-Test-Framework/blob/master/USER%20MANUAL.md#quick-start

**Comment by Aman2612** [comment]
How is adding people different from training? I'm first entering the name, choosing train and then capturing images of the person in a timed fashion. When I then go to the recognition part I see a rectangle but not the name. Sorry I'm new to this and might be missing something completely.

**Comment by sladomic** [comment]
Np. Since it's a test framework, a lot of variables are provided to play around with it. Every time you change training variables you have to execute the training to apply it.

Adding a person only captures images of the person and stores them for later training. The train / test dropdown only determines in which directory the images will be stored, in case you want to have a training and test set.

**Comment by Aman2612** [comment]
So I first click on the 'Add person' button. Then it asks me to enter a name and choose training / testing. So do I choose training and click start? After this when I go to the detection view should it be showing the name I entered?

**Comment by sladomic** [comment]
After that you have to first press "Training" in the main menu and if it's successful you can go to Recognition View and will see your name.

**Comment by Aman2612** [comment]
Ahh, when I build the app using this code, there is no recognition view or training view. Is this code different from the one on the play store because that one works perfectly fine. Where can I find that source code?
