### ISSUE TITLE
Not recognizing (Nexus 5x 7.1.1)

### ISSUE THREAD

**Issue by elich11** [Qualeams/Android-Face-Recognition-with-Deep-Learning-Test-Framework#8]
onCameraFrame,
 ppF.getProcessedImage(img, PreProcessorFactory.PreprocessingMode.RECOGNITION);
returns null.
Seems it can't find the eyes.
Using the default settings, have 2 trained classes.

**Comment by sladomic** [comment]
Do you still have the issue? Can you give some more information?

There was an issue with eye detection but this should have been fixed a month ago.

**Comment by elich11** [comment]
I cloned the latest code 4 days ago, I tested it on Nexus5x and on Nexus5 in both cases it failed to recognize, and from the debug I did on Nexus5x, I saw that the origin was the eye detection.
As I said before, I used the default configuration, added 2 persons, and training was successful.
When I tried to recognize, it simply didn't detected , and always got out in this line of code (RecognitionActivity, onCameraFrame):

if(images == null || images.size() == 0 || faces == null || faces.length == 0 || ! (images.size() == faces.length)){
            // skip
            Log.i(TAG, "skipping image not processing");
            **return imgRgba;**
    }

This is because the images was null (and when I debugged a little more, I saw that it simply does not recognize the eyes).

Hope this helps,
If you need me to deeg a little more, please tell me, love to help.

**Comment by sladomic** [comment]
Do you have the latest library version? If not, try the following from the project root:
- git submodule init
- git submodule update --recursive

Did you add the 2 persons using the "Add Person" function? There it also should have had problems with the eyes.

Can you debug the getEyes function in the FaceDetection class (e.g. the if condition "if (rightEyes.empty() || leftEyes.empty() || rightEyes.toArray().length > 1 || leftEyes.toArray().length > 1)")

Thanks for the help

**Comment by elich11** [comment]
Do you have the latest library version? If not, try the following from the project root:

git submodule init
git submodule update --recursive

**OK, did it.
Using this:
versionCode 20
versionName "1.3.0"**

Did you add the 2 persons using the "Add Person" function? There it also should have had problems with the eyes.

**Did not have any problems, at the end, I got a toast "training successful"**

Can you debug the getEyes function in the FaceDetection class (e.g. the if condition "if (rightEyes.empty() || leftEyes.empty() || rightEyes.toArray().length > 1 || leftEyes.toArray().length > 1)")

**both leftEyes, and rightEyes are empty.
I did it a lot of times, and made sure that the picture have eyes and it has good quality.**

Thanks for the help

**No problem, please tell me how do you want to proceed.
I did this tests on nexus5 to make sure this is not related to arm64_v8a**

**Comment by sladomic** [comment]
Can you try this in the getEyes method:
FileHelper fh = new FileHelper();
MatName m = new MatName("ImageUsedInGetEyes", img);
fh.saveMatToImage(m, FileHelper.DATA_PATH);

Your image will be stored under /sdcard/Pictures/facerecognition/data. Maybe a preprocessing step is doing something strange.

I won't be able to work on it these days since I'm very busy with another project https://github.com/literacyapp-org/literacyapp-android

But I see, that you could help us with your WiFi Direct experience if you have some spare time?

**Comment by elich11** [comment]
Sure,
How can I help?
________________________________

**Comment by sladomic** [comment]
If you don't mind, you could join the Slack channel found under the literacyapp repository or send me an email to qualeams@gmail.com so I can write to you.

**Comment by sladomic** [comment]
@elich11 can you please try again with the latest release?
