### ISSUE TITLE
The BPI-M3 board with Android reboots sometimes when opens the Recognition View

### ISSUE THREAD

**Issue by pavlobu** [Qualeams/Android-Face-Recognition-with-Deep-Learning-Test-Framework#9]
I have a Banana Pi board BPI-M3 with Android OS on it.
When I access Recognition View sometimes the entire system reboots. I cant even target the reason of such behavior.
I tried to debug the board with `adb logcat` but the latest logs don't even say that the system is going to reboot. The latest logs belong to the test app.

I'm so confused for now. What can be the reason of such behavior? Is it a hardware problem? Or maybe the system reboots when the CPU is overloaded. CPU consumption sometimes jumps up to 100% maybe this causes the board reboot?

**Comment by sladomic** [comment]
Hi,

I also think that the CPU consumption is the problem.

I had the same issue when I was doing a lot of work simultaneously on a Google Pixel C (although this tablet is a beast). I started 2 huge background jobs at the same time. Then I tried to use the RecognitionView and sometimes this also lead to a reboot (in the logcat I could only find lines stating, that the process has died).

Also see this:
http://stackoverflow.com/a/11269482/7388005

**Comment by pavlobu** [comment]
Thanks sladomic for an informative reply! 
I've continued testing the app and I also checked some forums about the Raspberry Pi, hoping to find some boarding issues and answers on forums.

It turned out that the problem was actually in SD card. So I unplugged the card and since that no occasional reboots are happened. It is so strange though.

Anyway thanks for you reply and have a nice day!

**Comment by pavlobu** [comment]
Hi @sladomic. I still got this reboot problem. The solution is not in SD card.
Now I have even more interesting problem. I target that sometimes when I quit recognize activity with "back" button, the main menu opens for a second and then all app crashes with the OutOfMemory exception:

here is the log:

```
E/AndroidRuntime( 1703): java.lang.OutOfMemoryError
E/AndroidRuntime( 1703): 	at android.media.FaceDetector.fft_initialize(Native Method)
E/AndroidRuntime( 1703): 	at android.media.FaceDetector.<init>(FaceDetector.java:117)
E/AndroidRuntime( 1703): 	at ch.zhaw.facerecognitionlibrary.PreProcessor.PreProcessor.setFaces(PreProcessor.java:66)
E/AndroidRuntime( 1703): 	at ch.zhaw.facerecognitionlibrary.PreProcessor.PreProcessorFactory.getProcessedImage(PreProcessorFactory.java:109)
E/AndroidRuntime( 1703): 	at ch.zhaw.facerecognition.Activities.RecognitionActivity$1.run(RecognitionActivity.java:175)
E/AndroidRuntime( 1703): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime( 1703): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 1703): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 1703): 	at ch.zhaw.facerecognition.Helpers.LoopingThread.run(LoopingThread.java:28)
W/ActivityManager(  429):   Force finishing activity 1 ch.zhaw.facerecognition/.Activities.MainActivity
D/Gralloc (  222): Allocate 753664 Bytes cached memory via ion heap mask 1 successfully
W/IcingInternalCorpora( 1166): getNumBytesRead when not calculated.
D/Gralloc (  222): Allocate 3686400 Bytes cached memory via ion heap mask 1 successfully
I/ActivityManager(  429): Config changes=480 {1.0 ?mcc?mnc en_US ?layoutDir sw720dp w1280dp h647dp 160dpi lrg long land -touch -keyb/v/h -nav/h s.8}
V/ActivityManager(  429): Display changed displayId=0
I/InputReader(  429): Reconfiguring input devices.  changes=0x00000004
I/Process ( 1703): Sending signal. PID: 1703 SIG: 9

```

maybe this it the reason of reboots?

**Comment by pavlobu** [comment]
After clearing cache and clearing data of the app in settings I no longer get this exception.
It is weird that I had it because I have a 4.5 GB of storage memory on the eMMC chip on board.
And the reboot no longer occurs.

It is so strange behavior. It reboots sometimes and it doesn't other times. I'm still so confused.

**Comment by sladomic** [comment]
Try this in the onCameraFrame method (e.g. before the return line). This should free the memory after every frame. I already use it in another project with the OpenCV camera view. If it's successful in your setup I could include it in the code.

```java
System.runFinalization();
Runtime.getRuntime().gc();
System.gc();
```

**Comment by pavlobu** [comment]
Thanks!  Going to try this right now. I'll give you feedback in a moment.

**Comment by pavlobu** [comment]
@sladomic Thank you very much! It looks it is working for now!
It slightly increased CPU consumption and made camera preview more laggy. But I already created separate thread for detection and recognition processes so now it is doing all stuff on background and camera preview is smooth (~ 25-30 FPS)

I'll give you feed back in couple days just to make sure I don't get this error anymore and reboot issue.

**Comment by sladomic** [comment]
@hexenskull Thanks for the update.

I just didn't have time to update this code but I also use background threads for the heavy tasks in the other project. If you want to contribute your code however you can do it.

**Comment by pavlobu** [comment]
Yes I would like to! But for now it is kinda unfinished yet. I will figure out how to add USB camera integration and will add this to the app as well. When I finish it, sure I want to share this!

It will be my first time contribution in project like this though but I'm excited about it and I want to help somehow.

**Comment by pavlobu** [comment]
@sladomic Hi. I still have this reboot problem. One more interesting thing I should admit is that reboot occasionally happens only first 20 minutes of running the board and doesn't happen again during the rest of the day. 
So I guess it could be hardware problem.

The OutOfMemory error never appears again. Thanks!

**Comment by sladomic** [comment]
@hexenskull can you please retest with the latest version? You can decrease the video size, so the CPU should struggle less
